== Les temps du passé

Jeanine peine à tenir en place alors que le jour qui passe semble durer une éternité.

Son cerveau jubile et fourmille d'idées, bientôt suivies d'autant de questionnements.

Si les objets reviennent en arrière dans le temps comme dans l'espace, comment se fait-il qu'il ne retrouvent pas leur état d'origine ?

Maintenant que ces vingt ans de recherche touchent à leur aboutissement, qu'est-ce que Jeanine va bien pouvoir faire de sa création ?

Que se passera-t-il si cette invention tombe entre de mauvaises mains ?

Que peut-elle faire pour la protéger ?

Que de questions, que de questions...

"`Madame ?`"

Ah, oui, c'est vrai. Il y a ce doctorant aussi. Qui a la désagréable habitude de la traiter comme si elle était une vieille dame respectable et un poil gâteuse.

[%hardbreaks]
"`Oui ?
— Euh... vous me le signez, ce papier ?`"

Jeanine griffone son visa sur la demande d'heures de vacations de l'intrus, ricanant intérieurement en relisant les premières lignes. "`Collaborateur Expert`", sérieusement ? Il vont inventer quoi, demain, comme titre pour les thésards au service des contrats, "`Lèche-bottes en chef`" ? Il faudrait qu'elle aille boire un thé avec Loga Bigoune, un de ces quatres, pour rire ensemble des absurdités qu'on fait avaler à ces marmots. Enfin bon...

[%hardbreaks]
"`Voilà, vous n'avez plus qu'à faire signer le CNRS, l'université de Chambéry, l'IUT de Valence, et l'école d'ingénieur Phelma, et vous êtes prêt à enseigner au sein de l'université Grenoble-Alpes !
— Pardon ?!?
— Oh, je veux dire tout est en ordre, excusez-moi, je pensais à quelqu'un d'autre...
— Ah... euh... ouf... très bien. Au revoir madame !`"

Parfois, la sénilité a aussi du bon.

L'importun parti, Jeanine peut de nouveau se concentrer sur des considérations plus pressantes. Par exemple, quel va être le prochain test qu'elle va effectuer pour évaluer le bon fonctionnement de sa machine ?

Si elle a bel et bien compris le comportement d'objets inanimés, dans ce cas elle doit maintenant évaluer dans quel mesure sa machine est sûre pour des êtres vivants. Si possible en commençant par des êtres vivants qu'elle n'apprécie que modérément.

"`Hum... Je me demande si je n'aurais pas vu courir une araignée sur le mur de ma salle de bains, l'autre jour !`"

Cependant, Jeanine se dit ensuite qu'une araignée n'est peut-être pas le meilleur choix de cobaye :

* Elle cherche un cobaye dont elle peut facilement dire qu'il a passé du temps dans la machine. Dans le cas d'une araignée, ce ne sera le cas que si il lui prend l'envie de tisser une toile, décision que cette dernière peut prendre longtemps à prendre.
* Elle veut pouvoir évaluer l'état de santé du cobaye à la fin de l'expérience. Or, elle ne sait absolument pas ce qui caractérise une araignée en bonne santé.

En fait, le cobaye idéal serait peut-être une limace ou un escargot. Un truc qui laisse une trace de bave partout sur son passage, et passe son temps à avancer en ligne droite sauf quand il se sent menacé. Mais difficile d'en trouver dans le jardin en hiver...

L'ignoble chihuahua des voisins peut-être ? Si il venait à succomber à l'expérience, elle pourrait le jeter sous une voiture et faire croire à un accident... Enfin, non, quelle horreur ! 0ù son esprit est-il donc en train de s'égarer ?

C'est amusant, quand même, que ce choix soit si difficile... Si Jeanine avait été un savant fou de dessin animé, elle n'aurait pas eu tant de scrupules et aurait simplement enlevé deux gamins au sortir d'une école pour les enfermer dans la machine en leur promettant une sucette. Ceci dit, la plupart des dessins animés n'explorent pas en profondeur la faisabilité d'enlever des mineurs dans un monde envahi par la paranoïa sécuritaire, où l'on doit montrer sa carte d'identité à un vigile rien que pour acheter du pain...

Jeanine soupire. Elle piétine, elle y réfléchit trop. Il faut qu'elle prenne le temps de laisser un peu ses idées décanter. Elle ouvre sa boîte mail pour se changer les idées, et massacre la trentaine d'indésirables qui y ont pris place depuis ce matin, puis elle attrape la pile de dossiers qui ont été déposés sur le bord gauche de son bureau et entreprend de les vérifier, tartiner de rouge ceux qui sont mal remplis, parapher sommairement ceux qui sont bien remplis, et déposer le résultat de ce traitement. Un travail assomant, mais c'est précisément dans cet ennui que réside sa dimension salutaire : il n'y a rien de tel qu'une pile de paperasse à vérifier pour se vider la tête.
