== Retour vers l'imparfait

Finalement, Jeanine a été gâtée, puisqu'elle aura eu l'occasion de faire les deux : détruire la relique maudite qu'elle avait exhumée de son grenier ET programmer la fonctionnalité correspondante sur ordinateur, après trois heures passées à essayer de faire cohabiter des circuits électroniques dont les composants ont 30 ans de décalage. Mais cette variété dans l'activité du chercheur n'est toutefois qu'une maigre consolation, lorsque l'on doit se réveiller le lendemain à une heure toujours bien trop matinale.

Ce matin-là, Jeanine a plus de mal que jamais à se détacher de ses draps. C'est comme si la durée de son sommeil, et le repos qu'elle en tire, étaient inversement proportionnels à l'avancement de ses recherches. A se demander si finalement, plutôt que les bizarreries de l'espace-temps, ce ne sont pas les habitudes de sommeil de Jeanine, en combinaison avec l'innatention qu'elles entraînent au quotidien, qui finiront par la tuer.

Peut-être est-elle déjà morte, pour ce qu'elle en sait. A partir d'un degré de manque de sommeil suffisant, tout le monde finit par ressembler furieusement à un zombie, et il paraît qu'on peut mourir en dessous d'une certaine dose de repos quotidien. Si ça se trouve, elle est en réalité dans le coma quelque part dans une chambre d'hôpital glauque, et les événements scientifiques de ces derniers jours ne sont qu'une fantaisie de son cerveau fatigué pour trouver le bonheur avant son dernier soupir. Hum.

Toutes ces réfléxions contiennent trop de spéculation capillotractée et pas assez de confiture. Jeanine se hâte donc de s'enfourner une bonne dose de cette dernière sur de solides tartines, pressée qu'elle est comme tous les matins. Puis avec un baillement, elle entame le long chemin qui la sépare de son quotidien.

La matinée est fraîche, trop fraîche, et Jeanine évite de peu la plaque de verglas sournoisement embusquée sur le trottoir qui tente de lui faire subir une deuxième dose de réveil-matin. La première suffisait, merci !

Entre deux arrêts de tram, Jeanine médite sur ce qu'elle fera du transporteur une fois ce dernier fonctionnel. C'est un point qu'elle n'a jamais vraiment considéré en détail. Pour elle, ses recherches sur le voyage temporel s'inscrivaient juste dans la continuité d'une longue tradition, poursuivie depuis la petite enfance, de dire "non" à tout principe naturel ou social qu'on lui impose comme une vérité universelle, mais qui l'incommode passablement.

Il y a certaines choses qu'elle sait d'avance ne PAS désirer faire. Par exemple commercialiser l'engin. Imaginez-donc une horde de fous furieux partant dans le passée comme si c'était un territoire inconnu en plein époque coloniale, en vue de faire subir à ce dernier tout ce qu'on faisait subir aux colonies en ce temps là : un remodelage en règle, conformément aux standards esthétiques de l'occupant. Et si les implications morales ne vous choquent pas encore, considérez ce qui se passerait dès lors que deux de ces voyageurs temporels se retrouveraient en désacord. La plus stupide des disputes infantiles ne serait qu'une boutade à côté de cela.

Mais plus inquiétants encore seraient ceux qui ne considérerait pas le passé comme le sujet d'une dispute d'individus immatures, mais comme le théâtre idéal pour élaborer des plans élaborés nourris au sein des plus noirs desseins. Ceux qui essaieraient de faire des expériences allant à l'encontre de l'intérêt général "pour voir". Ceux qui considéreraient cette machine comme l'occasion rêvée d'en finir avec une humanité qu'ils n'auraient jamais aimée...

Non. Jeanine regarde sans doute trop de films, mais malgré ça une chose semble claire : cette machine ne doit pas sortir de sa maison. En fait, elle devrait d'ors et déjà réfléchir aux moyens par lesquels elle pourrait s'assurer que si il lui arrive quelque chose, la machine se mette d'elle-même hors d'état de nuire.

Personne, absolument personne, ne doit savoir.

"`Gabriel Fauré !`"

Ah, oui, c'est vrai, elle a autre chose à faire que philosopher aujourd'hui. Genre trouver une expérience amusante à tenter qui puisse fournir un prétexte raisonnable pour mettre sa vie entre les mains d'un automate bricolé et encore mal testé. Ou sortir à cet arrêt et aller s'occuper du travail pour lequel on la paye.

Jeanine passe à un cheveu de manquer sa station. Elle est vraiment dans le pâté aujourd'hui.
