== A la recherche du temps perdu

Le lendemain, le réveil est effectivement rude.

Jeanine entr'ouvre les yeux à grand peine, localise l'instrument de torture dont le beuglement atroce l'a sortie de son sommeil douillet, et fait taire ce dernier d'une grande claque. Puis avec un soupir, elle se redresse, s'étire un grand coup, et va se préparer pour sa journée de labeur.

Les étages supérieurs de la maison de Jeanine offrent un contraste saisissant avec l'atmosphère chaotique de sa cave. Ici, l'ordre règne, établi et maintenu avec une minutie prussienne. Chaque chose a une place bien déterminée, et ne la quitte que dans un but bien précis, pour y retourner dès qu'elle n'est plus nécessaire. Pour Jeanine, cela fait partie d'une hygiène de vie de base que de séparer le travail, la maison, et la science, et cette différence de traitement est une des manières dont elle marque la séparation.

Le triumvirat précédent pourrait sembler étrange pour le non initié. Si Jeanine aime tant la science, pourquoi n'en ferait-elle pas son métier, tout simplement, au lieu d'étirer ses journées indéfiniment en prenant chaque jour un peu plus sur son temps de sommeil ? Mais quand on passe, comme Jeanine, beaucoup de temps par jour en compagnie de scientifiques de métier, on finit par bien connaître les compromis que la professionalisation de la recherche scientifique entraîne, de l'esclavagisme mafieux des autorités de financement à la falsification de résultats plus ou moins éhontée à laquelle chacun est un jour entraîné pour répondre à leurs demandes insensées.

En ce qui la concerne, Jeanine avait décidé qu'une telle manière de faire de la science n'était pas faite pour elle. Et ce d'autant plus qu'elle ne souhaitait pas voir ses résultats tomber entre les mains d'habitués de ce drôle de milieu.

Jeanine sort de la douche, et avale un petit déjeuner en coup de vent. Elle ne se laisse pas beaucoup de marge le matin, afin de pouvoir dormir un peu plus, mais ce choix se paye par une certaine précipitation en début de journée... avec une tartine encore enfoncée dans la bouche, Jeanine enfile son manteau, ses chaussures, attrape son sac, et se met en route pour l'arrêt de tram.

Chemin faisant, elle rumine les événements de la nuit. Qu'est-ce qui a bien pu mal tourner cette fois-ci ? Tout semblait bien fonctionner, et cette énergie qui s'est échappée de la machine sous forme de lumière devait bien provenir de quelque part... La théorie semblait solide, l'expérience aussi, et malgré tout, aucun effet observable n'était survenu... Plongée dans des abîmes de perplexité, Jeanine manque traverser la route sous le nez d'une voiture.

Après quelques échanges de politesses, chacun reprend sa route, et Jeanine se replonge dans son raisonnement. En admettant que les calculs soient justes et que les machines fonctionnent correctement, si l'expérience n'a pas fonctionné comme il faut, cela ne peut signifier qu'une chose : que c'est le raisonnement physique lui-même qui est incorrect. Elle a dû, à un moment ou à un autre, mal analyser le problème, en faisant une hypothèse inadéquate peut-être, ou bien en modélisant mal son protocole expérimental. C'est sans doute sur cela qu'elle devrait consacrer ses prochains efforts...

Jeanine doit prendre de la vitesse pour attrapper le tram qui arrive, ce qui l'arrache un temps à sa réflexion. Mais elle est néanmoins convaincue d'avoir fait un pas significatif en avant. Dès qu'elle aura un moment pour grifonner des notes à l'abri des regards indiscrets, elle prendra le temps de récapituler en détail ce qui s'est passé la veille, ce qu'elle en attendait, et en y ajoutant un schéma ou deux elle est convaincue qu'une erreur de raisonnement apparaîtra, claire comme de l'eau de roche.

Pour l'heure, néanmoins, Jeanine va devoir focaliser davantage son attention sur des considérations autrement moins excitantes...

"Gabriel Fauré !", l'avertit le tram. Jeanine descend du véhicule et se met en route vers le bâtiment administratif de l'Université Joseph Fourier, devenue Université de Grenoble, puis Université Grenoble Alpes. Comme la grande majorité des personnels de l'université, Jeanine aimerait bien tordre le cou aux politiques obsédés du classement de Shangai qui ont eu cette idée fantastique de changer le nom des universités tous les ans en y rajoutant à chaque fois une énorme masse de personnels à gérer en plus, mais aucun moyen humain supplémentaire du côté de l'administration. Deux théories sont très populaires au sein du département ressources humaines, l'une basée sur la stupidité, et l'autre sur la malveillance. Jeanine se range, sans hésiter une seconde, dans le groupe de ceux qui croient à la malveillance.

Jeanine rejoint son bureau, salue sa collègue stagiaire qui est déjà sur place depuis une heure, et entreprend d'éplucher sa boîte mail pour découvrir les nouveautés de la nuit. Vingt spams, douze mails généraux de l'université qu'on peut aussi raisonnablement ranger dans la catégorie des spames, et dix messages ne semblant pas être des spams à la seule lecture de leur sujet. Jeanine élimine d'un raccourci clavier expert les indésirables les plus évidents, puis se concentre sur les dix mails restants. Sur ces derniers, sept messages proviennent de personnes qui n'ont pas encore très bien compris la fonctionnalité "répondre à tous" de leur client mail, et rejoignent rapidement leurs trente-deux prédécesseurs. Jeanine soupire : c'est quand même terrible qu'en 2016, il y ait autant d'illetrés de la messagerie électronique dans la nature. On devrait sans doute essayer d'apprendre ça aux étudiants, au lieu de chercher à les plonger dès leur plus jeune âge dans le piège diabolique des suites bureautiques propriétaires.

Sur ces récriminations intérieures, Jeanine se penche sur les trois messages restants. Le premier est un message d'insulte envoyé par un professeur qui n'a manifestement rien compris au système de réservation des salles de cours, et estime pour une raison ou pour une autre que les secrétaires de direction sont responsables du fait qu'il se soit retrouvé à essayer de faire cours dans une salle déjà occupée. Jeanine émet un rire sec, et lui envoie pour toute réponse un lien vers le manuel de ce dernier.

Le message suivant est un spam un peu plus subtil que les autres, qui essaye de se faire passer pour un rappel de facturation afin que des comptables mal informés se précipitent sur sa pièce jointe, qui n'est autre qu'un exécutable malveillant. Jeanine l'élimine avec un soupir, en se disant que certaines de ses collègues seraient effectivement susceptibles de se faire prendre à ce piège. Enfin, le dernier message provient d'un ingénieur de mécanique très poli qui s'interroge sur la date de la prochaine formation en turbomachines. Jeanine lui répond tout aussi poliment en lui pointant virtuellement du doigt le site de la formation, et en mettant en copie la personne qui s'en charge.

L'ennemi électronique étant enfin pacifié, Jeanine émet un grognement victorieux puis va rejoindre ses collègues autour de la machine à café.
