== Les temps du passé

Jeanine peine à tenir en place alors que le jour qui passe semble durer une éternité.

Son cerveau jubile et fourmille d'idées, bientôt suivies d'autant de questionnements.

Si les objets reviennent en arrière dans le temps comme dans l'espace, comment se fait-il qu'il ne retrouvent pas leur état d'origine ?

Maintenant que ces vingt ans de recherche touchent à leur aboutissement, qu'est-ce que Jeanine va bien pouvoir faire de sa création ?

Que se passera-t-il si cette invention tombe entre de mauvaises mains ?

Que peut-elle faire pour la protéger ?

Que de questions, que de questions...

"`Madame ?`"

Ah, oui, c'est vrai. Il y a ce doctorant aussi. Qui a la désagréable habitude de la traiter comme si elle était une vieille dame respectable et un poil gâteuse.

[%hardbreaks]
"`Oui ?
— Euh... vous me le signez, ce papier ?`"

Jeanine griffone son visa sur la demande d'heures de vacations de l'intrus, ricanant intérieurement en relisant les premières lignes. "`Collaborateur Expert`", sérieusement ? Il vont inventer quoi, demain, comme titre pour les thésards au service des contrats, "`Lèche-bottes en chef`" ? Il faudrait qu'elle aille boire un thé avec Loga Bigoune, un de ces quatres, pour rire ensemble des absurdités qu'on fait avaler à ces marmots. Enfin bon...

[%hardbreaks]
"`Voilà, vous n'avez plus qu'à faire signer le CNRS, l'université de Chambéry, l'IUT de Valence, et l'école d'ingénieur Phelma, et vous êtes prêt à enseigner au sein de l'université Grenoble-Alpes !
— Pardon ?!?
— Oh, je veux dire tout est en ordre, excusez-moi, je pensais à quelqu'un d'autre...
— Ah... euh... ouf... très bien. Au revoir madame !`"

Parfois, la sénilité a aussi du bon.

L'importun parti, Jeanine peut de nouveau se concentrer sur des considérations plus pressantes. Par exemple, quel va être le prochain test qu'elle va effectuer pour évaluer le bon fonctionnement de sa machine ?

Si elle a bel et bien compris le comportement d'objets inanimés, dans ce cas elle doit maintenant évaluer dans quel mesure sa machine est sûre pour des êtres vivants. Si possible en commençant par des êtres vivants qu'elle n'apprécie que modérément.

"`Hum... Je me demande si je n'aurais pas vu courir une araignée sur le mur de ma salle de bains, l'autre jour !`"
