== Dans la gueule du loup

Le soir venu, Jeanine fonce à la cave pour se lancer avec frénésie dans les modifications requises. Sa décision est prise : le cobaye du prochain test, ce sera elle.

C'est la seule solution pour être fixée, en fin de compte. Depuis son test sur sa montre, elle sait que la machine a l'effet attendu, et ne représente pas de danger physique évident. Si maintenant elle mettait une boîte de Pétri pleine de moisissures, ou même un rat dans la machine, et les voyaient en sortir apparemment indemne, qu'est-ce qu'elle pourrait prouver de plus ? Que la machine ne semble pas mortelle à court terme ? Mais il y a tellement d'autres effets néfastes qu'elle pourrait avoir sur les êtres vivants... Et il serait difficile à Jeanine d'interroger des animaux, ou de tester l'évolution de leur état de santé sur plus d'une vingtaine d'années.

Que reste-t-il donc ? Mettre un autre être humain dans la machine ? Et donc le mettre dans la confidence, au risque d'une révélation des plus malheureuses ? Jeanine s'y refuse. Personne d'autre ne doit savoir. Si elle doit mourir dans cette expérience, eh bien elle emportera son secret dans la tombe, voilà tout. Et si elle doit en mourir longtemps après, eh bien au moins elle aura la satisfaction de ressembler à l'illustre Marie Curie sur au moins un point.

Reste toutefois certaines question scientifiques à gérer. Jeanine ne sait pour l'instant rien de l'effet de son transporteur sur la mémoire, et le cerveau humain en général. Pour ce qu'elle en sait, elle pourrait en sortir vidée de tout souvenir de son futur, et se retrouver ainsi piégée dans une boucle temporelle infinie où elle retournerait perpétuellement dans la machine au gré d'un état d'esprit demeurant inchangé, gagnant éventuellement en âge ce faisant jusqu'à mourir de vieillesse. Ce serait un triste destin. Pour éviter cela, il faut qu'elle ait un moyen sûr de transmettre des messages à son moi passé, même si il a tout oublié dans son voyage.

A priori, si elle maîtrise bien sa théorie, il ne sera pas trop difficile de trouver un tel moyen, se dit Jeanine tout en jetant un oeil vers le panneau de commandes de la machine.

Jeanine se dirige vers son établi, attrape le bloc de post-its qui s'y trouve, et en ôte le premier. Puis elle prend son stylo et écrit "`Si tu lis ce message, c'est que l'expérience a réussi`". Elle colle ensuite le post-it sur l'établi, puis se dirige vers le panneau de commandes du transporteur et, d'un geste expert, règle le compteur vert sur "`4384`". Puis elle retourne chercher son post-it sur l'établi, le place dans l'habitacle du transporteur, ferme ce dernier, et appuie sur le bouton.

'''

Jeanine se dirige vers son établi, attrape le bloc de post-its qui s'y trouve, et se prépare à en ôter le premier. Mais ce faisant, elle lit le message qui s'y trouve, et sourit. Tout va bien, elle dispose désormais d'un moyen de communiquer avec son moi passé si jamais les choses tournent mal. Il suffit d'emporter avec elle dans la machine un document écrit contenant des notes ou des instructions. Ce document reviendra certes à son point d'espace-temps d'origine, mais son contenu demeurera tel qu'il était en entrant dans la machine. De quoi contrer toute perte de mémoire qui pourrait survenir !

Satisfaite, Jeanine reprend ses modifications. Il s'agit principalement de rendre l'intérieur du transporteur plus douillet et hospitalier. Fort heureusement, ce n'est pas un problème de taille, juste de confort intérieur. Après tout, la machine a été conçue dès le départ pour transporter un être humain. Mais faute de tests et d'étude théorique suffisante, Jeanine ne sait pas vraiment à quoi s'attendre au moment du voyage. Le 4-déplacement dans l'espace-temps sera-t-il instantané ? Ou aura-t-elle la sensation de demeurer dans la machine pour une durée prolongée ? Tant de questions auxquelles elle aura, peut-être, la chance de découvrir la réponse. Si elle survit...

Jeanine se découvre une inquiétude tenace concernant la suite des événements, qui ne va pas sans l'agacer. Eh bien ! Que diable ! Lorsqu'elle avait commencé ce projet, elle savait qu'il y aurait des risques, au même titre qu'elle sentait venir les nombreuses déconvenues qu'elle avait toutes surmontées. Elle tentait là une expérience scientifique unique, un acte osé envers l'univers auquel elle ne connaissait aucun précédent. Ce qui ne signifiait pas qu'il n'y en avait pas eu, note... mais elle s'égare.

Jeanine se focalise davantage sur l'instant présent.
