== Prologue

Au détour d'un hiver qui peine à lâcher prise, une froide nuit sans lune s'est abattue sur la ville de Grenoble. Dehors, les rues sont désertes, à l'exception d'un cycliste ou d'un piéton égaré ici et là. A l'intérieur des bâtiments silencieux, chacun se réjouit de posséder un toit sur la tête et un chauffage en bon état de fonctionnement. Ou du moins, chaque personne concernée par de telles considérations. Quand aux autres, eh bien, ils s'emmitouflent un peu plus dans les étoffes en tout genre auxquelles ils doivent de ne pas congeler, et ils croisent les doigts pour que l'hiver finisse plus vite.

Dans la cave mal chauffée de sa petite maison au bord de l'Isère, Jeanine Victus résiste à la tentation de monter d'un étage pour retrouver la chaleur. Il y a quelque chose qu'elle souhaite terminer d'abord. Sirotant par intermittence un thé brûlant, comme une vaine tentative de surmonter le froid ambiant, elle laisse son stylo courir furieusement sur le feuillage un épais cahier que nul autre qu'elle n'a jamais lu -- et, si elle a son mot à dire, ne lira jamais. Sa main y trace d'un geste expert les formes de symboles mathématiques occultes et de schémas de principe élaborés alors qu'elle vérifie une dernière fois chaque point de son raisonnement, s'assure que tout semble en ordre. Il est des erreurs que l'on n'a pas envie de commettre.

Puis elle fait claquer sa langue contre ses dents d'un air satisfait, pose son stylo, change de page dans son grimoire, et se lève pour se diriger vers l'énorme machine qui orne le pan de mur adjacent à son bureau. Nul doute que lorsque l'architecte qui a conçu cette maison avait dessiné cette cave, ce n'était pas vraiment ce qu'il avait en tête. Il pensait sans doute plutôt que ce mur serait orné de bouteilles, comme les deux murs adjacents, tandis que le dernier mur serait le support d'un généreux garde-manger où l'on ferait sécher la charcuterie et garderait le fromage au frais. Et pendant un temps, il avait sans doute eu raison. Mais la dernière propriétaire en date avait décidé de réaménager un peu.

Face à Jeanine, en cette nuit froide, ce ne sont en effet pas dix rangées de bouteilles de Chartreuse qui se tiennent, ni même un jambon en attente de raclette, mais plutôt un énorme amas de métal, de câbles et d'appareils électroniques auquel l'oeil non exercé peinerait à attribuer une structure cohérente. Par ici, des appareils de mesures sont entassés les uns sur les autres, leur cadran à peine visible au milieu de la toile d'araignée de fil électrique dans laquelle ils sont enchevêtrés. Par là, on trouve un amas de tuyaux de cuivres couvert de valves au dessein obscur, connectés par un tuyau de caoutchouc à une grande bouteille d'acier qui émet en continu un chuintement menaçant.

"`Ah, soupire Jeanine, il faut vraiment que je range...`"

D'une main experte, elle extrait de ce bric à brac un tableau couvert de connecteurs électriques dont elle entreprend de tester, une par une, chaque branchement. En théorie, ce type de procédure ne devrait être requis chaque soir, mais seulement au moment de la construction d'un dispositif expérimental. Mais l'expérience montre que la théorie se trompe toujours quand elle essaye de prédire la durée de vie d'un dispositif physique. C'est pourquoi l'expérimentateur avisé vérifie toujours ses créations avant toute manipulation : on ne sait jamais quand une soudure effectuée trop tard dans la nuit d'avant va encore décider de sauter...

Sur un mur adjacent à celui où Jeanine s'affaire se trouve une énorme bibliothèque pleine à craquer, dont le contenu ne peut être qualifié que d'hétéroclite. Ici on trouve une pièce de théâtre de Shakespeare, "`As You Like It`". Là, un de ces essais scientifico-philosophiques sur la "`Métaphysique Quantique`". Perdu entre les deux, un ouvrage de référence sur les monades en programmation fonctionnelle ou la théorie des catégories. Au-dessus, une encyclopédie sur l'Egypte Ancienne. Dans un monde où la science est devenu une affaire de spécialistes, il est difficile de concevoir que Jeanine ait lu, ou même apréhendé, chacun de ces ouvrages. C'est pourtant le cas.

Ayant réparé _le_ fil qui a encore sauté, Jeanine émet un grognement impatient et plonge sans peur les mains dans l'amas de câbles pour en sortir ce qui semble être un panneau de contrôle, centralisant en un seul point diverses informations cruciales au bon déroulement de l'expérience. Jeanine sait bien que dans un monde informatisé, de tels panneaux sont devenus désuets, incapables de justifier leur prix et leur taux de panne élevé hormis lorsque des vies sont en jeu. Cependant, peut être en raison de son âge un peu avancé, elle ne peut pas s'empêcher de leur trouver un charme et une ergonomie qui manque à l'ordinateur lambda.

"`5.7°C`", dit un des afficheurs présents sur le panneau. Mais ce n'est pas celui qui intéresse Jeanine en l'occurence. L'objet de son attention est en effet un afficheur à diodes plus imposant que les autres, placé au centre du panneau, et dont la valeur affichée d'une puissante lumière rouge vif augmente au fil du temps suivant une logique connue d'elle seule.  "`891`", "`892`"... Par moment, le chiffre semble se figer un long moment, parfois plusieurs minutes, tandis qu'à d'autres moments il file plus vite que l'éclair. A une époque maintenant lointaine où ce panneau de commande était presque tout ce qui existait de la machine, Jeanine avait passé des mois à émettre théorie sur théorie concernant cette évolution irrégulière. Aujourd'hui, cela ne l'impressionne plus. Elle a compris... ou du moins, elle en est convaincue.

Sous le compteur imposant se trouve un gros potentiomètre, semblable à celui que l'on trouvait pour régler la fréquence porteuse sur les vieux postes de radio, peut-être parce que c'est sur un d'entre eux que Jeanine l'a récupéré. En dessous de ce dernier, un afficheur à diode similaire au précédent, mais dont la lumière est de couleur verte, et dont la valeur ne varie pas au fil du temps, figée qu'elle est sur un morne "`0`". Pas pour longtemps, cependant. Alors que Jeanine tend la main vers le potentiomètre et se met à le tourner, la valeur verte se met à augmenter en suivant les mouvements de celui-ci. Après un temps de réflexion, Jeanine la règle sur 1085. Cela devrait être suffisant.

Jeanine regarde sa montre. 03h42. Mon dieu... Le réveil va être rude. Nonobstant, elle décroche l'horloge portative de son poignet, et contemple un instant le ballet des aiguilles, en même temps qu'elle surveille le compteur rouge du coin de l'oeil. A 03h44, Jeanine se décide : elle ouvre une trappe sur le flanc de l'habitacle de la machine, insère la montre à l'intérieur de cette dernière, referme la trappe, et actionne un interrupteur avec une expression dramatique. Un flash aveuglant illumine alors le laboratoire.

'''

Jeanine regarde sa montre. 03h44. Mon dieu... Le réveil va être rude. Nonobstant, elle décroche l'horloge portative de son poignet, et contemple un instant le ballet des aiguilles, en même temps qu'elle surveille le compteur rouge du coin de l'oeil. A 03h46, Jeanine se décide : elle ouvre une trappe sur le flanc de l'habitacle de la machine, insère la montre à l'intérieur de cette dernière, referme la trappe, et actionne un interrupteur avec une expression dramatique. Un flash aveuglant illumine alors le laboratoire. Puis Jeanine, surexcitée, se précipite pour rouvrir la trappe, récupérer sa montre, et examiner cette dernière...

03h46. Jeanine fait une grimace. Encore raté. Elle ne comprend pas ce qui a échoué cette fois. Tout semblait en ordre, et elle avait refait chacun de ses calculs. Elle était tellement sûre...

Jeanine décide d'aller se coucher, dans l'espoir que la nuit lui porte conseille, tandis que dans les profondeurs de la cave, la machine est laissée à l'abandon. Sur son panneau de contrôle abandonné, les mesures continuent de s'égréner, sans spectateur pour les interpréter. Jeanine n'oserait jamais éteindre l'appareil, par peur que le lendemain il ne se rallume pas.

"`5.9°C`", dit le thermomètre à un monde qui n'a que faire de ses élucibrations.
